#!/usr/bin/env python3
"""Generate src/emoji_data.zig from the official Unicode emoji-test.txt.

Development only; the app never fetches anything at runtime.

    curl -sSfLo /tmp/emoji-test.txt https://unicode.org/Public/emoji/latest/emoji-test.txt
    python3 tools/gen_emoji_data.py /tmp/emoji-test.txt > src/emoji_data.zig
    zig fmt src/emoji_data.zig

Keeps every fully-qualified emoji except skin-tone variants (the base form of
each stays), in file order. Each record is "emoji|short name|aliases"; the
subgroup name (e.g. "heart", "hand-fingers-open") doubles as a keyword.
"""
import re
import sys

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}

# Everyday words the CLDR short names lack. Keys are fully-qualified emoji.
ALIASES = {
    "\U0001F602": "laugh lol haha",  # face with tears of joy
    "\U0001F923": "lol",  # rolling on the floor laughing
    "\U0001F604": "happy smile",  # grinning face with smiling eyes
    "\U0001F60A": "happy smile blush",  # smiling face with smiling eyes
    "\U0001F642": "smile",  # slightly smiling face
    "\U0001F44D": "like yes ok approve +1",  # thumbs up
    "\U0001F44E": "dislike no -1",  # thumbs down
    "❤️": "love like",  # red heart
    "\U0001F60D": "love",  # smiling face with heart-eyes
    "\U0001F618": "kiss love",  # face blowing a kiss
    "\U0001F64F": "thanks thank you please pray",  # folded hands
    "\U0001F62E": "wow surprised",  # face with open mouth
    "\U0001F632": "wow surprised shocked",  # astonished face
    "\U0001F622": "sad tear",  # crying face
    "\U0001F62D": "sad sob",  # loudly crying face
    "\U0001F525": "lit hot",  # fire
    "\U0001F389": "party celebrate tada congrats",  # party popper
    "\U0001F973": "party celebrate birthday",  # partying face
    "\U0001F44F": "clap applause bravo",  # clapping hands
    "\U0001F4AF": "hundred perfect",  # hundred points
    "\U0001F914": "hmm think",  # thinking face
    "\U0001F44C": "ok perfect",  # OK hand
    "✅": "done yes check",  # check mark button
    "\U0001F440": "look see",  # eyes
    "\U0001F91D": "deal agree",  # handshake
    "\U0001F4AA": "strong muscle",  # flexed biceps
    "\U0001F605": "phew nervous",  # grinning face with sweat
    "\U0001F644": "whatever",  # face with rolling eyes
    "\U0001F621": "angry mad",  # enraged face
    "\U0001F620": "angry mad",  # angry face
}

LINE = re.compile(r"^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$")


def main(path):
    version = "?"
    group = subgroup = None
    groups, subgroups, subgroup_group = [], [], []
    records, record_subgroup = [], []
    seen = set()
    with open(path, encoding="utf-8") as handle:
        for raw in handle:
            line = raw.rstrip("\n")
            if line.startswith("# Version:"):
                version = line.split(":", 1)[1].strip()
            elif line.startswith("# group:"):
                group = line.split(":", 1)[1].strip()
                groups.append(group)
            elif line.startswith("# subgroup:"):
                subgroup = line.split(":", 1)[1].strip()
                subgroups.append(subgroup)
                subgroup_group.append(len(groups) - 1)
            match = LINE.match(line)
            if not match:
                continue
            points = [int(p, 16) for p in match.group(1).split()]
            if any(p in SKIN_TONES for p in points):
                continue
            emoji = "".join(chr(p) for p in points)
            name = match.group(3).strip()
            assert "|" not in name and "\n" not in name, name
            assert emoji not in seen, name
            seen.add(emoji)
            records.append(f"{emoji}|{name}|{ALIASES.get(emoji, '')}")
            record_subgroup.append(len(subgroups) - 1)
    missing = set(ALIASES) - seen
    assert not missing, missing
    assert len(subgroups) < 256 and len(records) < 65535

    out = sys.stdout
    out.write("//! Generated by tools/gen_emoji_data.py from Unicode emoji-test.txt; do not edit.\n")
    out.write("//! Fully-qualified emoji without skin-tone variants, in Unicode order.\n\n")
    out.write(f'pub const unicode_version = "{version}";\n\n')
    out.write("pub const group_names = [_][]const u8{\n")
    for name in groups:
        out.write(f'    "{name}",\n')
    out.write("};\n\n")
    out.write("pub const subgroup_names = [_][]const u8{\n")
    for name in subgroups:
        out.write(f'    "{name}",\n')
    out.write("};\n\n")
    out.write("/// Group index of each subgroup.\n")
    out.write("pub const subgroup_group = [_]u8{\n")
    for index in range(0, len(subgroup_group), 24):
        out.write("    " + ", ".join(str(v) for v in subgroup_group[index:index + 24]) + ",\n")
    out.write("};\n\n")
    out.write("/// Subgroup index of each record.\n")
    out.write("pub const record_subgroup = [_]u8{\n")
    for index in range(0, len(record_subgroup), 24):
        out.write("    " + ", ".join(str(v) for v in record_subgroup[index:index + 24]) + ",\n")
    out.write("};\n\n")
    out.write("/// One record per line: emoji|CLDR short name|extra keywords.\n")
    out.write("pub const records =\n")
    for record in records:
        out.write(f"    \\\\{record}\n")
    out.write(";\n")


if __name__ == "__main__":
    main(sys.argv[1])
