#!/usr/bin/env python3
"""Generate src/shortcode_data.zig: Slack/GitHub (gemoji) shortcode aliases.

Development only; the app never fetches anything at runtime.

    curl -sSfLo /tmp/gemoji.json https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
    python3 tools/gen_shortcodes.py /tmp/gemoji.json src/emoji_data.zig > src/shortcode_data.zig
    zig fmt src/shortcode_data.zig

The CLDR names already in emoji_data.zig double as shortcodes at runtime
("woozy face" is :woozy_face:), so only gemoji aliases whose name differs from
that are stored. One line per emoji: the catalog emoji, then its aliases.
Flags are left out: :flag_germany: comes from the CLDR name.
"""
import json
import re
import sys


def norm(text):
    text = text.lower().replace("-", "_").replace(" ", "_")
    return re.sub(r"[^a-z0-9_+]", "", text)


def catalog(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        m = re.match(r"\s*\\\\(\S+)\|([^|]*)\|", line)
        if m:
            out[m.group(1).replace("️", "")] = (m.group(1), norm(m.group(2)))
    return out


cat = catalog(sys.argv[2])
lines = []
for entry in json.load(open(sys.argv[1], encoding="utf-8")):
    if entry["category"] == "Flags":
        continue
    key = entry["emoji"].replace("️", "")
    if key not in cat:
        continue
    full, cldr = cat[key]
    names = [a for a in entry["aliases"] if a != cldr]
    if names:
        lines.append(full + " " + " ".join(names))
print("//! Generated by tools/gen_shortcodes.py from github/gemoji; do not edit.")
print("pub const aliases =")
print("\n".join("    \\\\" + l for l in lines))
print("    ;")
